<details>
                <summary>Chemistry</summary>
                <p>Chemistry is the scientific study of the composition, structure, properties, and reactions of matter. It explores the behavior of atoms and molecules and how they interact to form different substances. Key areas of chemistry include:
                <br><br>
                Organic Chemistry: The study of carbon-containing compounds.
                <br><br>
                Inorganic Chemistry: The study of compounds that do not contain carbon.
                <br><br>
                Physical Chemistry: The study of the physical principles underlying chemical processes.
                <br><br>
                Analytical Chemistry: The study of the methods used to analyze the composition of matter.
                <br><br>
                Biochemistry: The study of chemical processes within and relating to living organisms.
                </p>
            </details>
            <details>
                <summary>Biology</summary>
                <p>Biology is the scientific study of life and living organisms, including their physical structure, chemical processes, molecular interactions, physiological mechanisms, development, and evolution. It covers a vast range of topics, such as:
                <br><br>
                Zoology: The study of animals.
                <br><br>
                Botany: The study of plants.
                <br><br>
                Microbiology: The study of microorganisms.
                <br><br>
                Genetics: The study of genes, heredity, and variation in living organisms.
                <br><br>
                Ecology: The study of the relationships between organisms and their environment.</p>
            </details>
            <details>
                <summary>Earth Science</summary>
                <p>Earth science is a branch of science dealing with the physical constitution of the Earth and its atmosphere. It encompasses various disciplines, including: 
                <br><br>
                Geology: The study of the Earth's solid matter, its structure, and its history.
                <br><br>
                Oceanography: The study of the Earth's oceans, including their physical properties, chemical composition, and life forms.
                <br><br>
                Meteorology: The study of the Earth's atmosphere, weather patterns, and climate.
                <br><br>
                Climatology: The study of long-term weather patterns and climate change.
                <br><br>
                Paleontology: The study of ancient life forms preserved in rocks.</p>
            </details>
